** Week 1, 20 points

choose two possible papers/figures and write a PDF description
(including pseudocode) of how to the original authors computed their
results and created their figures (e.g. SVM for figure figure, random forest for second figure). 
Include a copy of the original
figure (with citation) and write at least one paragraph for each of:
problem setting, data sources, algorithms studied (including
baselines). 

Detailed rubric:

10 points for each figure,
- 2 points for copy of original figure.
- 2 points for citation, for example: Hastie, et al. Elements of
  Statistical Learning, Figure 3.7.
- 2 points for problem setting paragraph. What are the inputs,
  outputs, and desired function to learn?
- 2 points for the data sources paragraph. Describe the real-world
  problem (e.g. predicting survival times of cancer patients using
  features measured at diagnosis), and where you plan to obtain the
  data set, or how to plan to create the data set. For real-world
  data, put a URL where you will download it; for simulated data,
  describe how you will create it. Describe the data set dimensions:
  how many rows/observations and columns/features in the inputs X?
  What do the labels y look like? Show the first few rows/observations
  from the data set, if possible.
- 2 points for a paragraph describing the algorithms studied,
  including baselines. Use pseudo-code to explain what algorithms you
  plan to code during your project, and to explain how you will
  compute the numbers that are plotted in the figure that you chose.
  Describe what you will learn about in your coding project.

** Week 2, 10 points

present your two choices to your partner. Write an opinion about what
you think your partner should choose. 

- 4 points for a paragraph summarizing what your partner intends to do if his/her first figure is used for the coding project. 
- 4 points for a paragraph about the second figure.
- 2 points for a paragraph describing your opinion about what would be better learning experience.

** Week 3, 10 points

Choose one of the two figures, and begin coding your implementation for your chosen figure 
(e.g. choose SVM, dont do random forest), submit your
preliminary code to a github repo. Include your PDF from week one, and a README that describes how someone else could re-do your analysis (e.g. typing "make" at the command line will re-do all the analyses, and produce the final figure-5.3.png).
- 0 points for no github repo.
- 1-3 points for a github repo with minimal code.
- 4-6 points for a github repo with your PDF description from week 1, and a README describing your project.
- 7-10 points for a github repo with substantial code, and a Makefile that documents how to make your figure.

** Week 4, 10 points

continue working on your figure, and code review your partner’s github
repo. Write suggestions in a PDF file and send it to me and your
partner. There should be two paragraphs
- the first paragraph should describe the documentation that your partner has provided about how to re-do the analysis (README and Makefile). 5 points (1 point for each of the following)
  - Does the README clearly explain the purpose of the repository / coding project?
  - Does the README have a link to the PDF project proposal?
  - Does the README have a copy of the figure?
  - Does the README have a citation to where the figure came from?
  - Does the Makefile clearly document the commands that can be run to reproduce the analysis?
- the second paragraph should describe the code that your partner has written so far. 5 points (1 point for each of the following).  If the answer is NO to any of the following, please provide suggestions about how to improve.
  - Is the code easy to read / understand?
  - Does the code contain any comments that explain what the code is doing?
  - Does the code contain any repetition that could be avoided by writing functions/loops/vectorization?
  - Does the code run without errors?
  - Does the code produce a figure?

** Week 5, 30 points

your figure and code are due along with a report explaining exactly
what you did (explain what happened if you were unable to exactly
reproduce the figure) 

** Week 6, 20 points

run your partner’s code and write a report explaining whether or not
you could reproduce your partner’s results. 10 points for your report
about your partner, 10 points if your code was reproducible by your
partner.
